---
---
# Source: guppy/templates/cm-guppy-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: "guppy-config"
data:
  guppy_config.json: |-
    
    {
      "indices": [
          {
              "index": "etl",
              "type": "case"
          },
          {
              "index": "file",
              "type": "file"
          }
      ],
      "config_index": "etl_array-config",
      "auth_filter_field": "auth_resource_path"
    }
---

# Source: guppy/templates/service.yaml
kind: Service
apiVersion: v1
metadata:
  name: guppy-service
spec:
  selector:
    app: guppy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      name: http
      nodePort: null
  type: ClusterIP
---

# Source: guppy/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guppy-deployment
spec:
  selector:
    # Only select pods based on the 'app' label
    matchLabels:
      app: guppy
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: guppy
        public: "yes"
        # GEN3_DATE_LABEL
        aadpodidbinding: azure-pod-identity-binding-selector
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - guppy
              topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      volumes:
        - name: guppy-config
          configMap:
            name: guppy-config
      containers:
        - name: guppy
          image: "quay.io/cdis/guppy:latest"
          livenessProbe:
            httpGet:
              path: /_status
              port: http
            initialDelaySeconds: 30
            periodSeconds: 60
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /_status
              port: http
          ports:
          - name: http
            containerPort: 8000
          env:
          - name: GUPPY_PORT
            value: "8000"
          - name: GUPPY_CONFIG_FILEPATH
            value: /guppy/guppy_config.json
          - name: GEN3_ES_ENDPOINT
            value: elasticsearch-master.elasticsearch.svc.cluster.local:9200
          - name: GEN3_ARBORIST_ENDPOINT
            value: http://arborist-service/
          - name: TIER_ACCESS_LEVEL
            value: libre
          volumeMounts:
            - name: "guppy-config"
              readOnly: true
              mountPath: "/guppy/guppy_config.json"
              subPath: guppy_config.json
          command: ["/bin/bash"]
          args:
            - "-c"
            - |
              node --max-http-header-size 16000 dist/server/server.js;
            
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0.5
              memory: 1024Mi
            limits:
              cpu: 1
              memory: 2400Mi
---

# Source: guppy/templates/spc-guppy.yaml
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: guppy-azure-kvname
spec:
  provider: "azure" # Only supporting Azure right now
  parameters:
    usePodIdentity: 'true'
    keyvaultName: gen3-dev-ceok-kv
    cloudName: 'AzurePublicCloud'
    resourceGroup: rg-gen3-dev 
    subscriptionId: b59451c1-cd43-41b3-b3a4-74155d8f6cf6 
    tenantId: 72f988bf-86f1-41af-91ab-2d7cd011db47

